version: '3.8' 

services:
  db:
    image: postgres:latest  
    container_name: cubos-movies-postgres
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: 123456  
      POSTGRES_DB: cubos-movies-db  
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:  # Criação do volume