export enum MovieStatus {
  RELEASED = 'RELEASED',
  IN_PRODUCTION = 'IN_PRODUCTION',
  POST_PRODUCTION = 'POST_PRODUCTION',
  PRE_PRODUCTION = 'PRE_PRODUCTION',
  CANCELLED = 'CANCELLED',
  ON_HOLD = 'ON_HOLD',
}
